### ISSUE TITLE
Late response of the results

### ISSUE THREAD

**Issue by dharantej1** [ThilakReddyy/JNTUHRESULTS-SERVICE#55]
First of all this is a great idea as well as a very well presented web application, but after the final year results i found that the results are taking more time than usually or sometimes even dont load the results. Can you please fix this issue or the bug. I have tried on almost all the devices (Android, iphone, Mac and Windows), the issue persists on all platforms browsers!

Thanks again!

**Comment by ThilakReddyy** [comment]
Hello @dharantej1 ,

Sorry for the late reply!!

The website is working fine now. The academic results are now available on the JNTUH RESULTS. Have made some improvements to enhance result retrieval speed through a caching system.

If you encounter any difficulties while checking your results, I kindly request your patience. In such cases, waiting for 5-10 minutes and then trying again should resolve any issues, allowing you to access your results smoothly.

If you have any questions or concerns, kindly revert back to me.

Thank you for your understanding and congratulations on your academic achievements!
